AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Template to deploy resources of the streaming price benchmark system

Resources:
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${AWS::StackName}-DependenciesLayer"
      Description: Contains the python dependencies. 
      ContentUri: dependencies/.
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12

  OriginalSearchesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-OriginalSearchesQueue"

  FilteredSearchesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-FilteredSearchesQueue"

  SampledSearchesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-SampledSearchesQueue"

  DecoratedSearchesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-DecoratedSearchesQueue"

  PrimerInvoke:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: InitStackFunction
    Properties:
      ServiceToken: !GetAtt InitStackFunction.Arn

  InitStackFunction:
    Type: AWS::Serverless::Function
    DependsOn: 
      - DecoratedSearchStorageNamespace
      - DecoratedSearchStorageWorkGroup
    Properties:
      Description: Initializes the Redshift database by creating the recommendations table
      CodeUri: src/InitStackFunction
      Handler: app.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          DB_NAME: !Sub "${AWS::StackName}-decorated-search-storage-db"
          WORKGROUP_NAME: !Sub "${AWS::StackName}-decorated-search-storage-wg"
      Policies: 
        - Version: '2012-10-17'
          Statement: 
            - Effect: Allow
              Resource: !GetAtt DecoratedSearchStorageWorkGroup.Workgroup.WorkgroupArn
              Action: 
                - redshift-data:ExecuteStatement
                - redshift-serverless:GetCredentials

  PublishMessageFunction:
    Type: AWS::Serverless::Function
    DependsOn: 
      - OriginalSearchesQueue
    Properties:
      CodeUri: src/PublishMessage
      Handler: app.lambda_handler
      Runtime: python3.12
      MemorySize: 512
      Timeout: 90
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          QUEUE_URL: !Sub "${OriginalSearchesQueue}"
          SOURCE_BUCKET_NAME: travel-data-samples
      Policies: 
        - SQSSendMessagePolicy:
            QueueName: !GetAtt OriginalSearchesQueue.QueueName
        - S3ReadPolicy:
            BucketName: travel-data-samples
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Enabled: false

  FilterLambdaFunction:
    Type: AWS::Serverless::Function
    DependsOn: 
      - OriginalSearchesQueue
      - FilteredSearchesQueue
    Properties:
      CodeUri: src/FilterLambda
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 15
      Environment:
        Variables:
          QUEUE_URL: !Sub "${FilteredSearchesQueue}"
      Policies: 
        - SQSSendMessagePolicy:
            QueueName: !GetAtt FilteredSearchesQueue.QueueName
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt OriginalSearchesQueue.Arn
            BatchSize: 10
            Enabled: true
            
  SampleLambdaFunction:
    Type: AWS::Serverless::Function
    DependsOn: 
      - FilteredSearchesQueue
      - SampledSearchesQueue
    Properties:
      CodeUri: src/SampleLambda
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 20
      Environment:
        Variables:
          COUNTER_DYNAMODB_TABLE: !Ref StratifiedSamplingCountersTable
          QUEUE_URL: !Sub "${SampledSearchesQueue}"
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref StratifiedSamplingCountersTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt SampledSearchesQueue.QueueName
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt FilteredSearchesQueue.Arn
            BatchSize: 10
            Enabled: true

  GetCurrencyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/GetCurrencyLambda
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 15
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          CURRENCY_CACHE_TABLE: !Ref CurrencyCacheTable
          API_URL: https://data-api.ecb.europa.eu/service/data/EXR/D..EUR.SP00.A
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CurrencyCacheTable
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(17 0 * * ? *)
            Enabled: false

  DecorateLambdaFunction:
    Type: AWS::Serverless::Function
    DependsOn: 
      - SampledSearchesQueue
      - DecoratedSearchesQueue
    Properties:
      Layers: 
        - !Ref DependenciesLayer
      CodeUri: src/DecorateLambda
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 20
      Environment:
        Variables:
          CURRENCY_CACHE_TABLE: !Ref CurrencyCacheTable
          QUEUE_URL: !Sub "${DecoratedSearchesQueue}"
      Policies: 
        - SQSSendMessagePolicy:
            QueueName: !GetAtt DecoratedSearchesQueue.QueueName
        - DynamoDBReadPolicy:
            TableName: !Ref CurrencyCacheTable      
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SampledSearchesQueue.Arn
            BatchSize: 10
            Enabled: true

  StratifiedSamplingCountersTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Sub "${AWS::StackName}-StratifiedSamplingCountersTable"
      AttributeDefinitions: 
        - AttributeName: ond_and_date
          AttributeType: S
      KeySchema: 
        - AttributeName: ond_and_date
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DecoratedSearchStorageNamespace:
    Type: AWS::RedshiftServerless::Namespace
    Properties:
      NamespaceName: !Sub "${AWS::StackName}-decorated-search-storage-ns"
      DbName: !Sub "${AWS::StackName}-decorated-search-storage-db"

  DecoratedSearchStorageWorkGroup:
    Type: AWS::RedshiftServerless::Workgroup
    Properties:
      WorkgroupName: !Sub "${AWS::StackName}-decorated-search-storage-wg"
      NamespaceName: !Ref DecoratedSearchStorageNamespace
      BaseCapacity: 32

  CurrencyCacheTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Sub "${AWS::StackName}-CurrencyCacheTable"
      AttributeDefinitions: 
        - AttributeName: currency_type
          AttributeType: S
      KeySchema: 
        - AttributeName: currency_type
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
        
Outputs:
  PublishMessageFunctionUrlEndpoint:
      Description: "Publish Function URL Endpoint"
      Value:
        !GetAtt PublishMessageFunctionUrl.FunctionUrl